
project_id = "lhhxxnbfdrkvjjbzxdjs"

[functions.guesty-reservation-webhook]
verify_jwt = false

[functions.guesty-listing-sync]
verify_jwt = false

[functions.guesty-sync]
verify_jwt = false

[functions.guesty-auth]
verify_jwt = false

[functions.guesty-auth-check]
verify_jwt = false

