
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888

# Required environment variables for integrations:
# GUESTY_USERNAME - Guesty account username
# GUESTY_PASSWORD - Guesty account password
# GUESTY_CLIENT_ID - OAuth client ID from Guesty
# GUESTY_SECRET - OAuth client secret from Guesty
# STRIPE_SECRET_KEY - Stripe API secret key
# STRIPE_WEBHOOK_SECRET - Stripe webhook signing secret

