// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiulwmwjyhqrkvitigdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdWx3bXdqeWhxcmt2aXRpZ2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mzg1MjEsImV4cCI6MjA3MDQxNDUyMX0.90y5W9YbF1F_y8bjFZzaNkhuqw55rAByhHaQa_XstIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});